services:
  traefik:
    container_name: ${CONTAINER_NAME}-traefik
    env_file: .env
    restart: always
    image: traefik:v3.2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/acme.json
    networks:
     - traefik-network
    command: --configFile=/etc/traefik/traefik.yml
networks:
  traefik-network:
    external: true
~                  
