services:
  database:
    container_name: ${CONTAINER_NAME}-mariadb
    image: mariadb
    env_file: .env
    restart: always
    environment:
        MYSQL_DATABASE: ${DATABASE_NAME}
        MYSQL_USER: ${DATABASE_USERNAME}
        MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      # ports:
      #   - "3306:3306"
    networks:
      - wp-db-network
    volumes:
      - ./database-data:/var/lib/mysql

  phpmyadmin:
    container_name: ${CONTAINER_NAME}-phpmyadmin
    image: phpmyadmin
    env_file: .env
    environment:
        PMA_HOST: database
        PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    networks:
      - wp-db-network
        #  ports:
        # - "8081:80"

volumes:
  dbdata: {}

networks:
  wp-db-network:
    external: true

